services:
  db:
    image: postgres:latest
    container_name: persona_ai
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=persona_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example

volumes:
  persona_ai: {}